### ISSUE TITLE
Change machine type to single core high mem

### ISSUE THREAD

**Issue by pwoods25443** [GlobalFishingWatch/pipe-segment#36]
We are using `n1-highmem-2` to get more memory which is needed for the monthly run, but this also has 2 cores which we don't really use since the process is not multi-threaded.

Consider changing to a custom machine type such as `custom-1-12800-ext`

And then maybe set the max number of workers to 200 instead of 100

**Comment by pwoods25443** [comment]
@bitsofbits is the claim I made above really true?  I just checked the CPU use on some instances running the segmenter in dataflow on `n1-highmem-2` machines, and it seems to be using 100% CPU even though the job is not multi-threaded.   Perhaps dataflow is smart enough to run two processes at the same time?

**Comment by bitsofbits** [comment]
@pwoods25443 , I'm not sure. I always assumed it was one process per core. But I don't think that's based on anything. Either way though, you want to be able to assign more memory per core though -- I think all the highmem instances have the same amount of memory per core.
