### ISSUE TITLE
Test Run January 2015

### ISSUE THREAD

**Issue by pwoods25443** [GlobalFishingWatch/pipe-segment#7]
Do a test run with a month of data for the old and new segment algorithms for comparison with prior analyses

- [x] January 2015 v.0.8 [Completed]( https://console.developers.google.com/project/world-fishing-827/dataflow/job/2017-10-02_11_47_58-18148148216652323823)
`world-fishing-827:scratch_paul.pipe_segment_v0_8_2015_01`
- [x] January 2015 v.0.9-alpha [Completed](https://console.developers.google.com/project/world-fishing-827/dataflow/job/2017-10-02_11_41_24-13760175924596254056) 
`world-fishing-827:scratch_paul.pipe_segment_v0_9_alpha_2015_01`

- [x] Review and comment - commentary here https://github.com/SkyTruth/gpsdio-segment/issues/41

**Comment by davidkroodsma** [comment]
@pwoods25443 I need this rerun with tagblock station so that I can identify satellite versus terrestrial receivers...

**Comment by pwoods25443** [comment]
@davidkroodsma any other fields you need included?  I'm working on automatic schema detection so that we can pass through  all the fields, but for now I have to specify them explicitly.

**Comment by pwoods25443** [comment]
This testing and analysis resulted in the release of gpsdio-segment v0.9
