### ISSUE TITLE
Legacy tables did not get schema change in segment_info and vessel_info

### ISSUE THREAD

**Issue by pwoods25443** [GlobalFishingWatch/pipe-segment#78]
The existing tables `segment_identity_daily_*` and `segment_vessel_daily_*` did not get updated when #71 was deployed to `pipe_production_b`.  

A field `ident_count` was added to these tables in #71

This causes a silent failure when generating `segment_info` and `vessel_info` because both compute `sum(ident_count)` and for the tables where the field is not present, this value is NULL which spoils the most_common computation for identity values.

### Solutions

1) re-run `segment-identity-daily` for all days, and re-run all downstream operations in `pipe-segment`

2) patch `segment_info` and `segment_vessel_daily` to derive `ident_count` as `msg_count - pos_count` if `ident_count` is null

**Comment by enriquetuya** [comment]
We have re-run the segmenter pipeline so this is not needed anymore.
